x-common: &common
  stdin_open: true
  tty: true
  volumes:
    - .:/opt/parallel
  working_dir: /opt/parallel
  cap_add:
    - SYS_PTRACE
  security_opt:
    - seccomp:unconfined
  ulimits:
    core: 99999999999
  entrypoint: /bin/bash

services:
  php:
    <<: *common
    image: ghcr.io/krakjoe/php-${PHP_BUILD:-release}-${PHP_VERSION:-8.5}:${PHP_IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/php.dockerfile
      args:
        PHP_SRC_TYPE: ${PHP_SOURCE:-dist}
        PHP_SRC_DEBUG: ${PHP_SRC_DEBUG:-disable}
        PHP_SRC_ASAN: ${PHP_SRC_ASAN:-disable}
        PHP_SRC_GCOV: ${PHP_SRC_GCOV:-disable}
        PHP_VERSION_MAJOR: ${PHP_VERSION_MAJOR:-8}
        PHP_VERSION_MINOR: ${PHP_VERSION_MINOR:-5}
        PHP_VERSION_PATCH: ${PHP_VERSION_PATCH:-0}
        PHP_VERSION_RC: ${PHP_VERSION_RC:-RC2}

  parallel:
    <<: *common
    image: ghcr.io/krakjoe/parallel-${PHP_BUILD:-release}-${PHP_VERSION:-8.5}:${PHP_IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: docker/parallel.dockerfile
      args:
        PHP_SRC_TYPE: ${PHP_BUILD:-release}
        PHP_SRC_ASAN: ${PHP_SRC_ASAN:-disable}
        PHP_SRC_GCOV: ${PHP_SRC_GCOV:-disable}
        PHP_VERSION: ${PHP_VERSION:-8.5}
        PHP_IMAGE_TAG: ${PHP_IMAGE_TAG:-latest}
