version: '3.6'

x-aliases:
  - &parallel
      stdin_open: true
      tty: true
      volumes:
        - .:/opt/parallel
      working_dir: /opt/parallel
  - &build
      context: .
      args:
        - PHP_SRC_TYPE
        - PHP_SRC_DEBUG
        - PHP_SRC_OPCACHE
        - PHP_VERSION_MAJOR
        - PHP_VERSION_MINOR
        - PHP_VERSION_PATCH
        - PHP_VERSION_RC
  - &dev
      cap_add:
        - SYS_PTRACE
      security_opt:
        - seccomp:unconfined
      ulimits:
        core: 99999999999
      entrypoint: /bin/bash

services:
  "php-8.0": {      <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/php.dockerfile,
      args: {
        UBUNTU_VERSION_MAJOR: 22,
        UBUNTU_VERSION_MINOR: "04",
        PHP_SRC_TYPE:         dist,
        PHP_SRC_DEBUG:        enable,
        PHP_SRC_OPCACHE:      disable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    0,
        PHP_VERSION_PATCH:    23,
      }
    },
    container_name:  php-dist-8.0.23,
    image:           php-dist-8.0.23:parallel,
    <<: *dev
  }
  "parallel-8.0": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/parallel.dockerfile,
      args: {
        PHP_SRC_TYPE:         dist,
        PHP_SRC_DEBUG:        enable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    0,
        PHP_VERSION_PATCH:    23,
      }
    },
    container_name:  parallel-dist-8.0.23,
    image:           parallel-dist-8.0.23:latest,
    depends_on:      [php-8.0],
    <<: *dev
  }
  "php-8.1": {      <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/php.dockerfile,
      args: {
        UBUNTU_VERSION_MAJOR: 22,
        UBUNTU_VERSION_MINOR: "04",
        PHP_SRC_TYPE:         dist,
        PHP_SRC_DEBUG:        enable,
        PHP_SRC_OPCACHE:      disable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    1,
        PHP_VERSION_PATCH:    11,
      }
    },
    container_name:  php-dist-8.1.11,
    image:           php-dist-8.1.11:parallel,
    <<: *dev
  }
  "parallel-8.1": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/parallel.dockerfile,
      args: {
        PHP_SRC_TYPE:         dist,
        PHP_SRC_DEBUG:        enable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    1,
        PHP_VERSION_PATCH:    11,
      }
    },
    container_name:  parallel-dist-8.1.11,
    image:           parallel-dist-8.1.11:latest,
    depends_on:      [php-8.1],
    <<: *dev
  }
  "php-8.2": {      <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/php.dockerfile,
      args: {
        UBUNTU_VERSION_MAJOR: "22",
        UBUNTU_VERSION_MINOR: "04",
        PHP_SRC_TYPE:         git,
        PHP_SRC_DEBUG:        enable,
        PHP_SRC_OPCACHE:      disable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    2,
        PHP_VERSION_PATCH:    0,
        PHP_VERSION_RC:       RC4,
      }
    },
    container_name:  php-git-8.2.0,
    image:           php-git-8.2.0:parallel,
    <<: *dev
  }
  "parallel-8.2": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/parallel.dockerfile,
      args: {
        PHP_SRC_TYPE:         git,
        PHP_SRC_DEBUG:        enable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    2,
        PHP_VERSION_PATCH:    0,
      }
    },
    container_name:  parallel-git-8.2.0,
    image:           parallel-git-8.2.0:latest,
    depends_on:      [php-8.2],
    <<: *dev
  }