version: '3.6'

x-aliases:
  - &parallel
      stdin_open: true
      tty: true
      volumes:
        - .:/opt/parallel
      working_dir: /opt/parallel
      environment:
        - PHP_SRC_GCOV=disable
  - &build
      context: .
  - &ubuntu
      UBUNTU_VERSION_MAJOR: "22"
      UBUNTU_VERSION_MINOR: "04"
  - &php
      PHP_SRC_TYPE:         dist
      PHP_SRC_DEBUG:        enable
      PHP_SRC_ASAN:         disable
      PHP_SRC_GCOV:         disable
  - &dev
      cap_add:
        - SYS_PTRACE
      security_opt:
        - seccomp:unconfined
      ulimits:
        core: 99999999999
      entrypoint: /bin/bash

services:
  # PHP-8.0
  "php-dbg-8.0": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/php.dockerfile,
      args: {       <<: *ubuntu, <<: *php,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    0,
        PHP_VERSION_PATCH:    24,
      }
    },
    container_name:  php-dbg-8.0,
    image:           parallelphp/php-dbg-8.0:8.0.24,
    profiles:        [php-8.0,dbg],
    <<: *dev
  }
  "php-gcov-8.0": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/php.dockerfile,
      args: {       <<: *ubuntu, <<: *php,
        PHP_SRC_GCOV:         enable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    0,
        PHP_VERSION_PATCH:    24,
      }
    },
    container_name:  php-gcov-8.0,
    image:           parallelphp/php-gcov-8.0:8.0.24,
    profiles:        [php-8.0,gcov],
    <<: *dev
  }
  "php-release-8.0": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/php.dockerfile,
      args: {       <<: *ubuntu, <<: *php,
        PHP_SRC_DEBUG:        disable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    0,
        PHP_VERSION_PATCH:    24,
      }
    },
    container_name:  php-release-8.0,
    image:           parallelphp/php-release-8.0:8.0.24,
    profiles:        [php-8.0,release],
    <<: *dev
  }

  # parallel + PHP-8.0
  "parallel-dbg-8.0": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/parallel.dockerfile,
      args: {       <<: *php,
        PHP_SRC_TYPE:         dbg,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    0,
        PHP_VERSION_PATCH:    24,
      }
    },
    container_name:  parallel-dbg-8.0,
    image:           parallelphp/parallel-dbg-8.0:latest,
    profiles:        [parallel-8.0,dbg],
    <<: *dev
  }
  "parallel-gcov-8.0": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/parallel.dockerfile,
      args: {       <<: *php,
        PHP_SRC_TYPE:         gcov,
        PHP_SRC_GCOV:         enable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    0,
        PHP_VERSION_PATCH:    24,
      }
    },
    container_name:  parallel-gcov-8.0,
    image:           parallelphp/parallel-gcov-8.0:latest,
    profiles:        [parallel-8.0,gcov],
    <<: *dev
  }
  "parallel-release-8.0": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/parallel.dockerfile,
      args: {       <<: *php,
        PHP_SRC_TYPE:         release,
        PHP_SRC_DEBUG:        disable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    0,
        PHP_VERSION_PATCH:    24,
      }
    },
    container_name:  parallel-release-8.0,
    image:           parallelphp/parallel-release-8.0:latest,
    profiles:        [parallel-8.0,release],
    <<: *dev
  }

  # PHP-8.1
  "php-dbg-8.1": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/php.dockerfile,
      args: {       <<: *ubuntu, <<: *php,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    1,
        PHP_VERSION_PATCH:    11,
      }
    },
    container_name:  php-dbg-8.1,
    image:           parallelphp/php-dbg-8.1:8.1.11,
    profiles:        [php-8.1,dbg],
    <<: *dev
  }
  "php-gcov-8.1": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/php.dockerfile,
      args: {       <<: *ubuntu, <<: *php,
        PHP_SRC_GCOV:         enable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    1,
        PHP_VERSION_PATCH:    11,
      }
    },
    container_name:  php-gcov-8.1,
    image:           parallelphp/php-gcov-8.1:8.1.11,
    profiles:        [php-8.1,gcov],
    <<: *dev
  }
  "php-asan-8.1": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/php.dockerfile,
      args: {       <<: *ubuntu, <<: *php,
        PHP_SRC_ASAN:         enable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    1,
        PHP_VERSION_PATCH:    11,
      }
    },
    container_name:  php-asan-8.1,
    image:           parallelphp/php-asan-8.1:8.1.11,
    profiles:        [php-8.1,asan],
    <<: *dev
  }
  "php-release-8.1": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/php.dockerfile,
      args: {       <<: *ubuntu, <<: *php,
        PHP_SRC_DEBUG:        disable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    1,
        PHP_VERSION_PATCH:    11,
      }
    },
    container_name:  php-release-8.1,
    image:           parallelphp/php-release-8.1:8.1.11,
    profiles:        [php-8.1,release],
    <<: *dev
  }
  # parallel + PHP-8.1
  "parallel-dbg-8.1": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/parallel.dockerfile,
      args: {       <<: *php,
        PHP_SRC_TYPE:         dbg,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    1,
        PHP_VERSION_PATCH:    11,
      }
    },
    container_name:  parallel-dbg-8.1,
    image:           parallelphp/parallel-dbg-8.1:latest,
    profiles:        [parallel-8.1,dbg],
    <<: *dev
  }
  "parallel-gcov-8.1": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/parallel.dockerfile,
      args: {       <<: *php,
        PHP_SRC_TYPE:         gcov,
        PHP_SRC_GCOV:         enable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    1,
        PHP_VERSION_PATCH:    11,
      }
    },
    container_name:  parallel-gcov-8.1,
    image:           parallelphp/parallel-gcov-8.1:latest,
    profiles:        [parallel-8.1,gcov],
    <<: *dev
  }
  "parallel-asan-8.1": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/parallel.dockerfile,
      args: {       <<: *php,
        PHP_SRC_TYPE:         asan,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    1,
        PHP_VERSION_PATCH:    11,
      }
    },
    container_name:  parallel-asan-8.1,
    image:           parallelphp/parallel-asan-8.1:latest,
    profiles:        [parallel-8.1,asan],
    <<: *dev
  }
  "parallel-release-8.1": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/parallel.dockerfile,
      args: {       <<: *php,
        PHP_SRC_TYPE:         release,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    1,
        PHP_VERSION_PATCH:    11,
      }
    },
    container_name:  parallel-release-8.1,
    image:           parallelphp/parallel-release-8.1:latest,
    profiles:        [parallel-8.1,release],
    <<: *dev
  }

  # PHP-8.2
  "php-dbg-8.2": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/php.dockerfile,
      args: {       <<: *ubuntu, <<: *php,
        PHP_SRC_TYPE:         git,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    2,
        PHP_VERSION_PATCH:    0,
        PHP_VERSION_RC:       RC5,
      }
    },
    container_name:  php-dbg-8.2,
    image:           parallelphp/php-dbg-8.2:8.2.0RC5,
    profiles:        [php-8.2,dbg],
    <<: *dev
  }
  "php-gcov-8.2": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/php.dockerfile,
      args: {       <<: *ubuntu, <<: *php,
        PHP_SRC_TYPE:         git,
        PHP_SRC_GCOV:         enable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    2,
        PHP_VERSION_PATCH:    0,
        PHP_VERSION_RC:       RC5,
      }
    },
    container_name:  php-gcov-8.2,
    image:           parallelphp/php-gcov-8.2:8.2.0RC5,
    profiles:        [php-8.2,gcov],
    <<: *dev
  }
  "php-asan-8.2": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/php.dockerfile,
      args: {       <<: *ubuntu, <<: *php,
        PHP_SRC_ASAN:         enable,
        PHP_SRC_TYPE:         git,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    2,
        PHP_VERSION_PATCH:    0,
        PHP_VERSION_RC:       RC5,
      }
    },
    container_name:  php-asan-8.2,
    image:           parallelphp/php-asan-8.2:8.2.0RC5,
    profiles:        [php-8.2,asan],
    <<: *dev
  }
  "php-release-8.2": { <<: *parallel,
    build: {           <<: *build,
      dockerfile: docker/php.dockerfile,
      args: { <<: *ubuntu, <<: *php,
        PHP_SRC_DEBUG:        disable,
        PHP_SRC_TYPE:         git,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    2,
        PHP_VERSION_PATCH:    0,
        PHP_VERSION_RC:       RC5,
      }
    },
    container_name:  php-release-8.2,
    image:           parallelphp/php-release-8.2:8.2.0RC5,
    profiles:        [php-8.2,release],
    <<: *dev
  }
  # parallel + PHP-8.2
  "parallel-dbg-8.2": { <<: *parallel,
    build: { <<: *build,
      dockerfile: docker/parallel.dockerfile,
      args: {        <<: *php,
        PHP_SRC_TYPE:         dbg,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    2,
        PHP_VERSION_PATCH:    0,
        PHP_VERSION_RC:       RC5,
      }
    },
    container_name:  parallel-dbg-8.2,
    image:           parallelphp/parallel-dbg-8.2:latest,
    profiles:        [parallel-8.2,dbg],
    <<: *dev
  }
  "parallel-gcov-8.2": { <<: *parallel,
    build: { <<: *build,
      dockerfile: docker/parallel.dockerfile,
      args: {        <<: *php,
        PHP_SRC_TYPE:         gcov,
        PHP_SRC_GCOV:         enable,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    2,
        PHP_VERSION_PATCH:    0,
        PHP_VERSION_RC:       RC5,
      }
    },
    container_name:  parallel-gcov-8.2,
    image:           parallelphp/parallel-gcov-8.2:latest,
    profiles:        [parallel-8.2,gcov],
    <<: *dev
  }
  "parallel-asan-8.2": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/parallel.dockerfile,
      args: {       <<: *php,
        PHP_SRC_ASAN:         enable,
        PHP_SRC_TYPE:         asan,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    2,
        PHP_VERSION_PATCH:    0,
        PHP_VERSION_RC:       RC5,
      }
    },
    container_name:  parallel-asan-8.2,
    image:           parallelphp/parallel-asan-8.2:latest,
    profiles:        [parallel-8.2,asan],
    <<: *dev
  }
  "parallel-release-8.2": { <<: *parallel,
    build: {        <<: *build,
      dockerfile:    docker/parallel.dockerfile,
      args: {       <<: *php,
        PHP_SRC_DEBUG:        disable,
        PHP_SRC_TYPE:         release,
        PHP_VERSION_MAJOR:    8,
        PHP_VERSION_MINOR:    2,
        PHP_VERSION_PATCH:    0,
        PHP_VERSION_RC:       RC5,
      }
    },
    container_name:  parallel-release-8.2,
    image:           parallelphp/parallel-release-8.2:latest,
    profiles:        [parallel-8.2,release],
    <<: *dev
  }