name: Linux

on:
  pull_request: null
  push:
    branches:
      - master
      - develop
      - release
  schedule:
    - cron: "30 4 * * *"

env:
  NODE_COVERALLS_DEBUG: true
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version: ["8.0", "8.1", "8.2", "8.3", "8.4", "8.5"]
        build: ["gcov", "release"]
        mode:
          - name: vanilla
            args: ""
          - name: opcache
            args: -d opcache.enable_cli=1 -d opcache.jit=disable
          - name: jit
            args: -d opcache.enable_cli=1 -d opcache.jit=function -d opcache.jit_buffer_size=32M
          - name: tracing jit
            args: -d opcache.enable_cli=1 -d opcache.jit=tracing -d opcache.jit_buffer_size=32M
    runs-on: ubuntu-latest
    name: Linux, PHP v${{matrix.version}}, ${{matrix.build}}, ${{matrix.mode.name}}
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Test parallel
        run: PHP_BUILD=${{matrix.build}} PHP_VERSION=${{matrix.version}} docker compose run --rm parallel docker/parallel.test ${{matrix.mode.args}}
      - name: Send Coverage
        if: ${{ matrix.build == 'gcov' }}
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ github.workspace }}/coverage.info
          flag-name: ${{matrix.mode.name}}-${{matrix.version}}
          parallel: true
  finish:
    if: always()
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Finish Coveralls
        uses: coverallsapp/github-action@v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
